export const PLAYLISTS = {
	"good": {
		title: "Feelin' Good!",
		color: "#FBBF24",
		songs: [
			"Mountain Song",
			"Bubblegum K.K.",
			"K.K. Calypso",
			"K.K. Country",
			"K.K. Groove",
			"K.K. Salsa",
			"K.K. Samba",
			"K.K. Ska",
			"K.K. Dixie",
			"K.K. Disco",
			"Café K.K.",
			"K.K. Parade",
			"K.K. Rockabilly",
			"K.K. March",
			"K.K. Mambo",
			"K.K. Mariachi",
			"Neapolitan",
			"Spring Blossoms",
			"K.K. Ragtime",
		],
	},
	"grumpy": {
		title: "Grumpy McGrumpy Face",
		color: "#374151",
		songs: [
			"K.K. Cruisin'",
			"Lucky K.K.",
			"Surfin' K.K.",
			"K.K. Safari",
			"K.K. Jongara",
			"K.K. Tango",
			"Imperial K.K.",
			"Rockin' K.K.",
			"K.K. House",
			"K.K. Adventure",
			"K.K. Flamenco",
			"K.K. Metal",
			"K.K. Rock",
			"K.K. Bazaar",
			"K.K. Steppe",
			"K.K. Casbah",
			"DJ K.K.",
			"Go K.K. Rider",
		],
	},
	"lazy": {
		title: "Lazy Bum",
		color: "#CE9BF6",
		songs: [
			"Aloha K.K.",
			"K.K. Stroll",
			"Pondering",
			"Soulful K.K.",
			"K.K. Jazz",
			"K.K. Swing",
			"Mr. K.K.",
			"K.K. Synth",
			"K.K. Fusion",
			"K.K. Bossa",
			"K.K. Moody",
			"K.K. Aria",
			"K.K. Love Song",
			"K.K. Reggae",
			"I Love You",
			"K.K. Island",
			"K.K. Faire",
			"Marine Song 2001",
			"Wandering",
			"My Place",
			"Forest Life",
		],
	},
	"sad": {
		title: "#sadboihours",
		color: "#1E40AF",
		songs: [
			"Two Days Ago",
			"Only Me",
			"K.K. Western",
			"K.K. Lament",
			"K.K. Chorale",
			"King K.K.",
			"K.K. Étude",
			"K.K. Sonata",
			"K.K. Milonga",
			"K.K. Ballad",
			"K.K. Lullaby",
			"K.K. Waltz",
			"K.K. Dirge",
			"Comrade K.K.",
			"Steep Hill",
			"Stale Cupcakes",
			"K.K. Condor",
		],
	},
	"unknown": {
		title: "*shrug*",
		color: "#EF4444",
		songs: [
			"Hypno K.K.",
			"K.K. Rally",
			"K.K. Marathon",
			"Agent K.K.",
			"K.K. Soul",
			"K.K. Song",
			"The K. Funk",
			"K.K. Blues",
			"K.K. Oasis",
			"K.K. Folk",
			"K.K. Technopop",
			"K.K. D&B",
			"To the Edge",
			"K.K. Gumbo",
			"Space K.K.",
		],
	},
};

export const TITLE_TO_ID = {
	"Agent K.K.": 1,
	"Aloha K.K.": 2,
	"Animal City": 3,
	"Bubblegum K.K.": 4,
	"Café K.K.": 5,
	"Comrade K.K.": 6,
	"DJ K.K.": 7,
	"Drivin'": 8,
	Farewell: 9,
	"Forest Life": 10,
	"Go K.K. Rider": 11,
	"Hypno K.K.": 12,
	"I Love You": 13,
	"Imperial K.K.": 14,
	"K.K. Adventure": 15,
	"K.K. Aria": 16,
	"K.K. Ballad": 17,
	"K.K. Bazaar": 18,
	"K.K. Birthday": 19,
	"K.K. Blues": 20,
	"K.K. Bossa": 21,
	"K.K. Calypso": 22,
	"K.K. Casbah": 23,
	"K.K. Chorale": 24,
	"K.K. Condor": 25,
	"K.K. Country": 26,
	"K.K. Cruisin'": 27,
	"K.K. D&B": 28,
	"K.K. Dirge": 29,
	"K.K. Disco": 30,
	"K.K. Dixie": 31,
	"K.K. Étude": 32,
	"K.K. Faire": 33,
	"K.K. Flamenco": 34,
	"K.K. Folk": 35,
	"K.K. Fusion": 36,
	"K.K. Groove": 37,
	"K.K. Gumbo": 38,
	"K.K. House": 39,
	"K.K. Island": 40,
	"K.K. Jazz": 41,
	"K.K. Jongara": 42,
	"K.K. Lament": 43,
	"K.K. Love Song": 44,
	"K.K. Lullaby": 45,
	"K.K. Mambo": 46,
	"K.K. Marathon": 47,
	"K.K. March": 48,
	"K.K. Mariachi": 49,
	"K.K. Metal": 50,
	"K.K. Milonga": 51,
	"K.K. Moody": 52,
	"K.K. Oasis": 53,
	"K.K. Parade": 54,
	"K.K. Ragtime": 55,
	"K.K. Rally": 56,
	"K.K. Reggae": 57,
	"K.K. Rock": 58,
	"K.K. Rockabilly": 59,
	"K.K. Safari": 60,
	"K.K. Salsa": 61,
	"K.K. Samba": 62,
	"K.K. Ska": 63,
	"K.K. Sonata": 64,
	"K.K. Song": 65,
	"K.K. Soul": 66,
	"K.K. Steppe": 67,
	"K.K. Stroll": 68,
	"K.K. Swing": 69,
	"K.K. Synth": 70,
	"K.K. Tango": 71,
	"K.K. Technopop": 72,
	"K.K. Waltz": 73,
	"K.K. Western": 74,
	"King K.K.": 75,
	"Lucky K.K.": 76,
	"Marine Song 2001": 77,
	"Mountain Song": 78,
	"Mr. K.K.": 79,
	"My Place": 80,
	Neapolitan: 81,
	"Only Me": 82,
	Pondering: 83,
	"Rockin' K.K.": 84,
	"Soulful K.K.": 85,
	"Space K.K.": 86,
	"Spring Blossoms": 87,
	"Stale Cupcakes": 88,
	"Steep Hill": 89,
	"Surfin' K.K.": 90,
	"The K. Funk": 91,
	"To the Edge": 92,
	"Two Days Ago": 93,
	Wandering: 94,
	"Welcome Horizons": 95,
};
